[package]
name = "tg-stars"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"

axum = {version = "0.7", features = ["tokio", "http1", "macros"]}
tokio = { version = "1", features = ["full", "macros"] }
tokio-util = {version = "0.7", features = ["io"]}
tower = "0.5"
tower-http = {version = "0.6", features = ["fs"]}
hyper = { version = "1", features = ["http1", "server", "client"] }

serde_json = { version = "1.0" }
serde = { version = "1.0", default-features = false, features = ["derive", "rc"] }

async-rusqlite = {version = "0.4"}
rusqlite = { version = "0.29", features = ["functions"] }

uuid = { version = "1.7", features = ["v4", "fast-rng"] }
lru = {version = "0.12"}

dotenv = "0.15"
dotenv_codegen = {version = "0.15"}

hmac = "0.12"
form_urlencoded = "1.2"
sha2 = "0.10"
hex = "0.4"

#ws server
fastwebsockets = { version = "0.7", features = ["upgrade"] }
http-body-util = { version = "0.1" }
hyper-util = { version = "0.1", features = ["tokio"] }

#dont add kick feature
integrations = { path = "../../yoml/integrations", features = []}

